//
//  SMRotaryWheel.m
//  RotaryWheelProject
//
//  Created by cesarerocchi on 2/10/12.
//  Copyright (c) 2012 studiomagnolia.com. All rights reserved.

#import <UIKit/UIKit.h>
#import "SMClove.h"



@interface BNPieChart : UIView {
    
@private
	
	// Variables useful for drawing.  (Avoid recomputing them too much.)
	CGFloat centerX;
	CGFloat centerY;
	CGFloat radius;
    
    // strong [All objects are retained.]
	
	// Each element is an NSNumber representing a float.
	// The values add up to 1.0.
	NSMutableArray* slicePortions;
	
	// Endpoints of the slices.  Always has size one more than slicePortions.
	NSMutableArray* slicePointsIn01;
	
	NSMutableArray* sliceNames;
	NSMutableArray* nameLabels;
    
    // Has BNColor elements.  If #slices > #colors, the colors cycle.
    // When nil (default), uses autogenerated colors and never cycles.
    NSArray *colors;
	
	CGColorSpaceRef colorspace;
	
	int fontSize;
}

@property (nonatomic, retain) NSMutableArray* slicePortions;
@property (nonatomic, retain) NSArray *colors;
@property (nonatomic,strong) UILabel *valueLabel;

@property (nonatomic,strong) NSString *shadowImage;
@property (nonatomic,strong) NSString *pinImage;
@property (nonatomic,strong) UIColor *color;

@property int value;

// Adds a slice with the given portion (fraction in the range 0.0-1.0),
// and name.  The name may be nil.
- (void)addSlicePortion:(float)slicePortion withName:(NSString *)name;

// Creates a sample pie chart in the given frame.
//+ (BNPieChart *)pieChartSampleWithFrame:(CGRect)frame;

@end



@protocol PieChartDelegate <NSObject>
@required
-(void)pinTouchEndWithValue:(float)value;
@optional
-(void)pinTouchProcessingWithValue:(float)value;

@end

@interface HPieChartView : UIView 

@property (nonatomic, strong) UIView *container;
@property (nonatomic, strong) NSMutableArray *cloves;
@property CGAffineTransform startTransform;
@property CGPoint wheelCenter;
@property (nonatomic ,retain) NSMutableArray * pie;

@property float startRad;//开始弧度
@property float endRad;//结束弧度
@property (nonatomic, strong) id<PieChartDelegate> pinDelegate;
@property (nonatomic, strong) BNPieChart* chart;

- (void) setPinValue:(float)value;//设置指针位置
- (id) initWithFrame:(CGRect)frame withNum:(int)num withArray:(NSMutableArray *)array startRad:(float)startRad endRad:(float)endRad;
- (void) initWheel;
- (void) buildClovesOdd;
//- (float) calculateDistanceFromCenter:(CGPoint)point;

@end


